services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    networks:
      - app-network
      
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/envanter
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0917033
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true  # Add this to see SQL queries
      - JAVA_TOOL_OPTIONS=-XX:+UseContainerSupport
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    networks:
      - app-network

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=envanter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0917033
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: